  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 15.0
  height: 15.0
  resolution: 0.05

  plugins:
  - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}
  # - {name: voxel_layer, type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
  - {name: voxel_layer, type: "costmap_2d::VoxelLayer"}

  voxel_layer:
    enabled: true
    origin_z: 0.0
    z_resolution: 0.05
    z_voxels: 10
    unknown_threshold: 0
    #mark_threshold: 2
    publish_voxel_map: true
    combination_method: 1
    observation_sources: camera_mark
    camera_mark:
      data_type: PointCloud2
      topic: realsense/depth/color/points
      sensor_frame: realsense_mountpoint
      marking: true
      clearing: true
      obstacle_range: 1.90
      raytrace_range: 2.00
      min_obstacle_height: 0.06
      max_obstacle_height: 3.00
      mark_threshold: 3
      observation_persistence: 2.0
  
  # voxel_layer:
  #   enabled: true
  #   voxel_decay: 1.5
  #   decay_model: 0
  #   voxel_size: 0.1
  #   track_unknown_space: true
  #   max_obstacle_height: 3.0
  #   unknown_threshold: 15
  #   mark_threshold: 0
  #   update_footprint_enabled: true
  #   combination_method: 1
  #   origin_z: 0.0
  #   publish_voxel_map: true
  #   transform_tolerance: 0.2
  #   mapping_mode: false
  #   map_save_duration: 60
  #   min_obstacle_height: 0.1
  #   observation_source: camera_clear camera_mark  
  #   camera_mark:    
  #     data_type: PointCloud2
  #     topic: realsense/depth/color/points
  #     marking: true
  #     clearing: false
  #     min_obstacle_height: 0.3     #default 0, meters
  #     max_obstacle_height: 3.0     #defaule 3, meters
  #     expected_update_rate: 0.0    #default 0, if not updating at this rate at least, remove from buffer
  #     observation_persistence: 0.0 #default 0, use all measurements taken during now-value, 0=latest 
  #     inf_is_valid: false          #default false, for laser scans
  #     clear_after_reading: true    #default false, clear the buffer after the layer gets readings from it
  #     filter: "voxel"              #default passthrough, apply "voxel", "passthrough", or no filter to sensor data, recommended to have at one filter on
  #     voxel_min_points: 0          #default 0, minimum points per voxel for voxel filter
  #   camera_clear:
  #     enabled: true                #default true, can be toggled on/off with associated service call
  #     data_type: PointCloud2
  #     topic: realsense/depth/color/points
  #     marking: false
  #     clearing: true
  #     min_z: 0.1                   #default 0, meters
  #     max_z: 7.0                   #default 10, meters
  #     vertical_fov_angle: 0.7      #default 0.7, radians
  #     horizontal_fov_angle: 1.04   #default 1.04, radians
  #     decay_acceleration: 1.       #default 0, 1/s^2. If laser scanner MUST be 0
  #     model_type: 0                #default 0 (depth camera). Use 1 for 3D Lidar

